export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_AREAS = "GET_AREAS";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_USERS = "GET_USERS";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const REMOVE_SHAKE = "REMOVE_SHAKE";
export const NEW_UNREAD_MESSAGE = "NEW_UNREAD_MESSAGE";
export const REMOVE_UNREAD_MESSAGE = "REMOVE_UNREAD_MESSAGE";